---

- name: copy decrypted public key to tmp
  connection: local
  copy:
    decrypt: yes
    dest: "{{ inventory_dir }}/temp/id_rsa.pub"
    src: "{{ inventory_dir }}/keys/id_rsa.pub.enc"
    mode: 0644

- name: Set authorized key for ssh_user copying it from decrypted vault file
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{ inventory_dir }}/temp/id_rsa.pub"