---

- name: install packages
  become: true
  apt:
    name:
      - vim
      - git
      - python3
      - python3-pip
      - docker.io
    state: latest

- name: set default user editor
  lineinfile:
    dest: "/home/{{ ansible_user }}/.profile"
    state: present
    line: "export EDITOR='vim'"
    regexp: "^export EDITOR="
    insertafter: EOF

- name: set default sudo editor
  become: true
  lineinfile:
    line: "Defaults editor=/usr/bin/vim"
    insertbefore: BOF
    state: present
    regexp: "^Defaults editor="
    dest: /etc/sudoers
    validate: 'visudo -cf %s'