---

- name: Make sure we have a 'wheel' group
  become: true
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

# TODO: create better fix than removing password line
- name: create a sudo user
  become: true
  user:
    name: "{{ ansible_user }}"
    state: present
    groups: "wheel"
    append: yes
    # password: "{{ ansible_ssh_pass }}"