---

- name: install packages
  become: true
  apt:
    name:
      - vim
    state: latest

- name: set default terminal editor
  lineinfile:
    dest: ~/.profile
    state: present
    line: "export EDITOR='vim'"
    regexp: "^export EDITOR="
    insertafter: EOF